---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: openvpn-instance
    box: debian/buster64
    memory: 512
    cpus: 1
    instance_raw_config_args:
      - "vbguest.auto_update = false"
    groups:
      - openvpn
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../openvpn.yml
  inventory:
    group_vars:
      openvpn:
        user: vagrant
        openvpn_dh: ./tests/dh_do_not_use.pem
verifier:
  name: testinfra
  lint:
    name: flake8
